### ISSUE TITLE
Weka, Scikit-learn, or other tools?

### ISSUE THREAD

**Issue by true-developer** [bawb77/Project-Erectus#4]
Choose which tool will be used for data analysis

**scikit-learn**
http://scikit-learn.org/stable/
https://www.youtube.com/watch?v=elojMnjn4kk&list=PL5-da3qGB5ICeMbQuqbbCOQWcS6OYBr5A

**Weka**
http://www.cs.waikato.ac.nz/ml/weka/    
https://www.youtube.com/watch?v=Fg2x_zM3YTo&list=PLzVF1nAqI9VmC96TbvOPMkXToSmBMHJn7

**Comment by benjamin-baxter** [comment]
Weka
